#!/usr/bin/env bash
# Configures an Nginx server to redirect to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

new_url="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.techspot.com permanent;"
nginx_config="/etc/nginx/sites-enabled/default"

sudo sed -i "s/server_name _;/$new_url/" "$nginx_config"



echo "Ceci n'est pas une page" > /var/www/html/404.html
new_url="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinte    rnal;\n\t}"

sudo sed -i "s/server_name _;/$new_url/" "$nginx_config"
sudo service nginx restart

