#!/usr/bin/env bash
#server that redirects to another page.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
new_url="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.techspot.com permanent;"
sudo sed -i "s/server_name _;/$new_url/" /etc/nginx/sites-enabled/default

# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart
