#!/usr/bin/env bash
# configure web-02 to be identical to web-01

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html

#redirection rule
new_url="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.techspot  .com permanent;"
nginx_config="/etc/nginx/sites-enabled/default"

sudo sed -i "s/server_name _;/$new_url/" "$nginx_config"

#show the error page
echo "Ceci n'est pas une page" > /var/www/html/404.html
new_url="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$new_url/" "$nginx_config"



# Add custom response header to know the server name for debugging
HOST_NAME=$(hostname)
HEADER="\\\n\tadd_header X-Served-By $HOST_NAME;\n"
FIND=$(grep "X-Served-By" /etc/nginx/sites-available/default)
if [[ -z $FIND ]]; then
    sed -i "23i $HEADER" "nginx_config"
fi




sudo service nginx restart
