#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    The value of the HTTP header is the hostname of the running server.

apt-get update
apt-get install -y nginx
nginx_config="/etc/nginx/sites-enabled/default"

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    add_header X-Served-By $HOSTNAME;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://techspot.com/;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > "$nginx_config"

service nginx restart
