#!/usr/bin/env bash
# Installs HAProxy version 2.9 with the following configurations:

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.9
apt-get update
apt-get install -y haproxy=2.9.\*

echo "ENABLED=1" >> /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 313389-web-01 100.27.11.38:80 check
    server 313389-web-01 107.23.156.4:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
